# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('plot', models.CharField(max_length=500)),
                ('actors', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=200)),
                ('rel_year', models.CharField(max_length=5)),
                ('rating', models.CharField(max_length=5)),
            ],
        ),
    ]
