# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ghibli', '0002_remove_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
